print("My name is Ramon Zeidi.")
print("My student ID is 2049061.")
print("R")
print("a")
print("m")
print("o")
print("n")
print("My name all capitalized is RAMON ZEIDI.")
my_summer_plans = ["This summer I plan to sleep, travel, work."]
print (*my_summer_plans)